### ISSUE TITLE
syntax warning from netaddr package

### ISSUE THREAD

**Issue by hackern0v1c3** [hackern0v1c3/CanaryPi#7]
receiving this warning in dockerhub version but not locally built version

/usr/local/lib/python3.8/site-packages/netaddr/strategy/__init__.py:189: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if word_sep is not '':

**Comment by joelparkerhenderson** [comment]
Fixed by https://salsa.debian.org/python-team/modules/python-netaddr/-/commit/aa0ad078d773505962b3a4840fb5291e03060471

**Comment by hackern0v1c3** [comment]
Thanks for the heads up @joelparkerhenderson .  I built a new version and this does seem to be cleared up.
